[project]
name = "day12"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "karishma9142", email = "karishmacair47050@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "dotenv>=0.9.9",
    "groq>=1.7.0",
    "numpy>=2.4.6",
    "sentence-transformers>=6.1.0",
]

[project.scripts]
day12 = "day12:main"

[build-system]
requires = ["uv_build>=0.12.21,<0.13.0"]
build-backend = "uv_build"
